---
# tasks file for apache

- hosts: 192.168.127.153
  tasks:
  - name: installation du serveur apache
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - httpd
      - nano
      - epel-release
